import { useEffect } from "react";
import { useParams, Navigate } from "react-router-dom";
import { useStore } from "@/lib/store";
import { formatDateTime } from "@/lib/format";

export function PdfReport() {
  const { id } = useParams();
  const { state } = useStore();
  const complaint = state.complaints.find((c) => c.id === id);

  useEffect(() => {
    if (complaint) {
      setTimeout(() => {
        window.print();
      }, 500);
    }
  }, [complaint]);

  if (!complaint) {
    return <Navigate to="/admin/operations" replace />;
  }

  const reporter = state.users.find((u) => u.id === complaint.studentId);
  const worker = state.workers.find((w) => w.id === complaint.assignedWorkerId);

  return (
    <div className="p-8 max-w-4xl mx-auto bg-white text-black min-h-screen font-sans">
      <div className="border-b-2 border-black pb-4 mb-6 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold uppercase tracking-tight">Work Order Report</h1>
          <p className="text-sm text-gray-500 mt-1">Meridian Institute of Technology - Estate Office</p>
        </div>
        <div className="text-right">
          <p className="text-lg font-bold">{complaint.publicId}</p>
          <p className="text-sm text-gray-500">{formatDateTime(complaint.createdAt)}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div className="space-y-4">
          <div>
            <h3 className="text-xs font-bold uppercase text-gray-400">Location</h3>
            <p className="text-lg font-semibold">{complaint.building}</p>
            {complaint.room && <p className="text-md">{complaint.room}</p>}
          </div>
          
          <div>
            <h3 className="text-xs font-bold uppercase text-gray-400">Priority & Category</h3>
            <p className="text-lg uppercase">
              <span className="font-bold">{complaint.priority}</span> &bull; {complaint.category}
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <div>
            <h3 className="text-xs font-bold uppercase text-gray-400">Assigned Technician</h3>
            <p className="text-lg font-semibold">{worker ? worker.name : "Unassigned"}</p>
            {worker && <p className="text-md">{worker.phone}</p>}
          </div>

          <div>
            <h3 className="text-xs font-bold uppercase text-gray-400">Reporter</h3>
            <p className="text-lg font-semibold">{reporter ? reporter.fullName : "Unknown"}</p>
            {reporter && <p className="text-md">{reporter.email}</p>}
          </div>
        </div>
      </div>

      <div className="mb-8">
        <h3 className="text-xs font-bold uppercase text-gray-400 mb-2">Issue Description</h3>
        <div className="border border-gray-300 p-4 rounded-md bg-gray-50">
          <h2 className="text-xl font-bold mb-2">{complaint.title}</h2>
          <p className="whitespace-pre-wrap">{complaint.description}</p>
        </div>
      </div>
      
      <div className="mt-16 pt-8 border-t border-gray-300 text-center text-xs text-gray-500">
        <p>This is an automated report generated by Campus IQ Operations.</p>
        <p>Printed on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}</p>
      </div>
    </div>
  );
}
